In [10]:
# importing all necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
# printing the head of the dataset
df = pd.read_csv('pcos_dataset.csv')
df.head()

,Age,BMI,Menstrual_Irregularity,Testosterone_Level(ng/dL),Antral_Follicle_Count,PCOS_Diagnosis
0,24,34.7,1,25.2,20,0
1,37,26.4,0,57.1,25,0
2,32,23.6,0,92.7,28,0
3,28,28.8,0,63.1,26,0
4,25,22.1,1,59.8,8,0

In [12]:
# checking the size of the dataset
df.shape

(1000, 6)

In [13]:
# There are 1000 rows and 6 features in this dataset - somewhat small

In [14]:
# checking for missing values
df_missing = df.isnull().sum()
df_missing

Age                          0
BMI                          0
Menstrual_Irregularity       0
Testosterone_Level(ng/dL)    0
Antral_Follicle_Count        0
PCOS_Diagnosis               0
dtype: int64

In [15]:
# There are no missing values in any of the features, but I still want to check for any odd/invalid values

In [16]:
# checking the ranges of the features
df.describe()

,Age,BMI,Menstrual_Irregularity,Testosterone_Level(ng/dL),Antral_Follicle_Count,PCOS_Diagnosis
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,31.771000,26.38700,0.530000,60.159500,17.469000,0.199000
std,8.463462,4.93554,0.499349,23.160204,7.069301,0.399448
min,18.000000,18.10000,0.000000,20.000000,5.000000,0.000000
25%,24.000000,21.90000,0.000000,41.700000,12.000000,0.000000
50%,32.000000,26.40000,1.000000,60.000000,18.000000,0.000000
75%,39.000000,30.50000,1.000000,80.300000,23.250000,0.000000
max,45.000000,35.00000,1.000000,99.800000,29.000000,1.000000

In [17]:
# checking data types for each feature
df.dtypes

Age                            int64
BMI                          float64
Menstrual_Irregularity         int64
Testosterone_Level(ng/dL)    float64
Antral_Follicle_Count          int64
PCOS_Diagnosis                 int64
dtype: object

In [18]:
# No categorical features, which means I don't have to worry about encoding anything later on :P

In [19]:
# using a function to check for outliers using IQR
def detect_outliers_iqr(data):
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data < lower_bound) | (data > upper_bound)]
    return outliers

In [20]:
# table showing a summary of each feature
feature_info = {}

for column in df.columns:
  feature_info[column] = {}

  # feature type sorting
  if df[column].dtype == 'int64' or df[column].dtype == 'float64':
    feature_info[column]['Type'] = 'Numerical'
    feature_info[column]['Range'] = f"{df[column].min()} - {df[column].max()}"

  # totaling missing values for each feature
  feature_info[column]['Missing Values'] = df[column].isnull().sum()

  # totaling outliers
  if feature_info[column]['Type'] == 'Numerical':
    outliers = detect_outliers_iqr(df[column])
    feature_info[column]['Outliers'] = len(outliers)

# actually outputting the table
feature_table = pd.DataFrame(feature_info).T
display(feature_table)

                                Type        Range Missing Values Outliers
Age                        Numerical      18 - 45              0        0
BMI                        Numerical  18.1 - 35.0              0        0
Menstrual_Irregularity     Numerical        0 - 1              0        0
Testosterone_Level(ng/dL)  Numerical  20.0 - 99.8              0        0
Antral_Follicle_Count      Numerical       5 - 29              0        0
PCOS_Diagnosis             Numerical        0 - 1              0      199

In [21]:
# checking what the outliers are in the 'PCOS_Diagnosis' feature
df_diag = df['PCOS_Diagnosis']
detect_outliers_iqr(df_diag)

13     1
14     1
27     1
28     1
33     1
      ..
975    1
978    1
983    1
988    1
989    1
Name: PCOS_Diagnosis, Length: 199, dtype: int64

In [22]:
# There are no actual outliers in this feature, it is simply picking up on all of the positive PCOS diagnoses